<!--
    Wrapper for FullCalendar, an open-source Javascript calendar.
    https://fullcalendar.io/docs/vue
    https://fullcalendar.io/docs#toc
-->
<!-- Notes for self:
Schedule is passed in two arrays:
  a. SelectedCourses -> Courses (All courses selected)
  b. Schedule (The specific courses/sections/custom events to add, generated by Cartesian
  c. Selected CustomEvents (All customevents selected)

  Alright, so we can keep the created() function if we pass in our selectedCourses,
  so we can push to CoursesComputed each individual event that stems from selectedCourses

  The outcome of the created() function is CoursesComputed, which is essentially the same format as Courses, so we can
  skip that function, unless for some reason the "searching for classes" needs that missing Promise api thing.

2. Events list must include a custom field:
  a. ID
  b. Title
  c. Time and Dates
  e1. Whether it is a lecture or a section
  e. An array of ids that links lectures and sections
  d. Whether it is selected or not
  d1. An array of ids that links similar classes
  f. An array of ids that shows concurrency (thus when reshowing/hiding it parses through the array, and then each element's array, etc.)
3. Then, when  user clicks on an event
  a. Check if it's already been selected or not
  b. If selected: unselect it and reshow all concurrent
  c. If currently unselected: Set selected, check if is is a CustomEvent (do nothing),Lecture (do nothing) or Section (Select corresponding Lecture, thus need a method function), then get rid of similar classes (and their sections), then get rid of concurrent classes (and their sections)

ADD NUMBER OF SEATS AVAILABLE TO EVENT TITLE FROM THIS.COURSES
-->
<template>
  <b-card no-body>
<!--    <template v-slot:header>-->
<!--      <div class="no-wrap d-flex flex-row align-items-center">-->
<!--        <span class="d-inline-block" tabindex="0">-->
<!--          <font-awesome-icon-->
<!--              v-if="schedule.favorited"-->
<!--              icon="heart"-->
<!--              size="sm"-->
<!--              :id="'favorite-icon'+_uid"-->
<!--              style="color: #ED0303;"-->
<!--              @click="unFavoriteSchedule(schedule)"-->
<!--          />-->

<!--          <font-awesome-icon-->
<!--              v-else-->
<!--              icon="heart"-->
<!--              size="sm"-->
<!--              :id="'favorite-icon'+_uid"-->
<!--              style="color: #FFC7C7;"-->
<!--              @click="saveSchedule(schedule)"-->
<!--          />-->
<!--        </span>-->

<!--        <b-tooltip-->
<!--            v-if="!$store.getters.userIsAuthenticated"-->
<!--            :target="'favorite-icon'+_uid">-->
<!--          Sign in to save schedules.-->
<!--        </b-tooltip>-->

<!--        <b-toast :id="'deleted-toast-' + _uid" title="You deleted a schedule!" variant="warning">-->
<!--          The schedule, "{{schedule.name}}" was deleted. Click the button to undo.-->
<!--          <b-button @click="saveSchedule(schedule)" variant="warning">Undo</b-button>-->
<!--        </b-toast>-->

<!--        <b-button-->
<!--            :id="'popover-button-sync-' + _uid"-->
<!--            variant="link"-->
<!--            ref="button"-->
<!--            @click="popoverShow = !popoverShow"-->
<!--        >{{ schedule.name }}</b-button>-->

<!--        <b-popover-->
<!--            :id="'popover'+ _uid"-->
<!--            :show.sync="popoverShow"-->
<!--            :target="'popover-button-sync-' + _uid"-->
<!--            placement="bottom"-->
<!--        >-->
<!--          <template v-slot:title>-->
<!--            <b-button @click="onClose" class="close" aria-label="Close">-->
<!--              <span class="d-inline-block" aria-hidden="true">&times;</span>-->
<!--            </b-button>Enter schedule name:-->
<!--          </template>-->
<!--          <b-row>-->
<!--            <b-col cols="10" class="px-2">-->
<!--              <b-form-input v-model="scheduleName"></b-form-input>-->
<!--            </b-col>-->
<!--            <b-col class="p-2">-->
<!--              <font-awesome-icon-->
<!--                  icon="check"-->
<!--                  size="sm"-->
<!--                  style="color: #428bca;"-->
<!--                  @click="saveName()"-->
<!--              />-->
<!--            </b-col>-->
<!--          </b-row>-->
<!--        </b-popover>-->

<!--        <div v-if="showEditButton">-->
<!--          <router-link v-on:click.native="editSchedule(schedule)" :to="{name:'home'}">-->
<!--            <font-awesome-icon-->
<!--                icon="edit"-->
<!--                size="sm" />-->
<!--          </router-link>-->
<!--        </div>-->

<!--      </div>-->
<!--    </template>-->
    <div v-if="doneLoading" class="weekly-calendar">
      <FullCalendar
          height="auto"
          :plugins="calendarPlugins"
          @hook:mounted="manuallyFixCSS"
          :events="events"
          :weekends="false"
          :columnHeaderText="columnHeaderText"
          allDaySlot="false"
          header="false"
          editable="false"
          :minTime="minTime"
          :maxTime="maxTime"
          @eventClick="eventClick"
          id="calendar"
      />
      <!--          :minTime="schedule.sortingAttributes.earliestBeginTime"-->
      <!--          :maxTime="schedule.sortingAttributes.latestEndTime"-->
    </div>
    <div v-else class="text-center">
      <b-spinner class="m-2" variant="primary" label="Spinning"></b-spinner>
    </div>
  </b-card>
</template>

<script>
import FullCalendar from "@fullcalendar/vue";
import timeGridPlugin from "@fullcalendar/timegrid";
import $ from "jquery";
// import api from "@/components/backend-api.js";
import {
  getBackgroundColor,
  getBorderColor,
} from "@/components/util/color-utils.js";
// import xss from "xss";

export default {
  components: {
    FullCalendar,
  },
  props: {
    courses: {
      type: Array,
      required: false
    },
    schedule: {
      type: Object,
      required: false,
    },
    showEditButton: {
      type: Boolean,
      default: false,
    }
  },
  data: function () {
    return {
      calendarPlugins: [timeGridPlugin],
      coursesComputed: [],
      doneLoading: false,
      savingScheduleInProgress: false,
      scheduleSavedStatus: null,
      scheduleName: this.schedule.name,
      popoverShow: false,
      errors: [],
      scheduleLocal: this.schedule,
      minTime: "07:00:00",
      maxTime: "22:00:00"
    };
  },
  created: function () {
    this.doneLoading = true;
  },
  mounted: function () {
    this.manuallyFixCSS();
  },
  computed: {
    /**
     * The schedules array is mapped to a format that can be passed to the WeeklySchedule component.
     * This array has the same length as the schedules array.
     */
    events: function () {
      console.log(JSON.stringify(this.schedule));
      return this.parseScheduleToEventList(this.schedule, this.courses);
    },
    quarter: function () {
      return this.$store.state.selectedQuarter;
    },
  },
  methods: {
    eventClick: function(arg) {
      console.log(JSON.stringify(arg.event.extendedProps[0]));
      arg.event.display
      // arg.event.display = "none";
      // console.log(JSON.stringify(arg.event.display));
      // console.log(JSON.stringify(arg.event.display));
      // arg.event.title = "none";
      // arg.event.eventdisplay = "none";
      // console.log(JSON.stringify(arg.event.title));
      // console.log(arg);
      // arg.event.setProp( 'display', 'none' );
      // var calendarEl = document.getElementById('calendar');
      // calendarEl.render();
      // $('#calendar').fullCalendar('updateEvent', arg);


      // arg.el.display = "none";
      // console.log(JSON.stringify(arg.el.display));

    },
    /**
     * Parses a schedule and maps the enroll codes to the data format for WeeklySchedule from courses.

     TODO: ADD THE NUMBER OF SPOTS AVAILABLE AS WELL TO SCHEDULE TITLE
     */
    parseScheduleToEventList: function (schedule, courses) { //this.schedule, this.courses
      const _this = this;

      function classSectionToFullCalendarEvent(classSection) {
        const course = courses.find(
            (course) => course.courseId == classSection.courseId
        );

        if (classSection.name != undefined) {
          //if it is a custom event
          const dayInt = {
            MONDAY: 1,
            TUESDAY: 2,
            WEDNESDAY: 3,
            THURSDAY: 4,
            FRIDAY: 5,
            SATURDAY: 6,
          };
          return {
            title: classSection.name,
            daysOfWeek: classSection.timeLocations[0].fullDays.map(
                (a) => dayInt[a]
            ),
            startTime: classSection.timeLocations[0].beginTime,
            endTime: classSection.timeLocations[0].endTime,
            color: getBackgroundColor(classSection.name),
            display: "none",
            extendedProps: ["gello"]
          };
        } else {
          return classSection.selectedEnrollCodes.map((section) =>
              _this.eventFromEnrollCode(section, course)
          );
        }
      }

      var totalevents = schedule.classes
          .map(classSectionToFullCalendarEvent)
          .flat(); //do this function to all of the classes
      var customevents = schedule.customEvents.map(
          classSectionToFullCalendarEvent
      );

      customevents.forEach((item) => {
        totalevents.push(item);
      })
      // console.log(JSON.stringify(totalevents));
      return totalevents;
    },
    /* Uses an enroll code and the course object to return an event object
     * that is compatible with FullCalendar.
     */
    eventFromEnrollCode: function (enrollcode, course) {
      const section = course.classSections.find(
          (section) => section.enrollCode == enrollcode
      );

      var titletodisplay = course.fullCourseNumber + ": " + enrollcode;
      const dayInt = {
        MONDAY: 1,
        TUESDAY: 2,
        WEDNESDAY: 3,
        THURSDAY: 4,
        FRIDAY: 5,
        SATURDAY: 6,
      };

      if (section.timeLocations.length == 1) {
        return {
          title: titletodisplay, //course.fullCourseNumber,
          daysOfWeek: section.timeLocations[0].fullDays.map((a) => dayInt[a]),
          startTime: section.timeLocations[0].beginTime,
          endTime: section.timeLocations[0].endTime,
          borderColor: getBorderColor(course.deptCode),
          backgroundColor: getBackgroundColor(course.courseId.slice(7, 14)),
          display: "none",
          extendedProps: ["gello"]
        };
      } else {
        var multipleevents = [];
        var multipletimeandplace = section.timeLocations;
        var classinfo = {
          title: titletodisplay, //course.fullCourseNumber,
          daysOfWeek: "",
          startTime: "",
          endTime: "",
          borderColor: getBorderColor(course.deptCode),
          backgroundColor: getBackgroundColor(course.courseId.slice(7, 14)),
          display: "none",
          extendedProps: ["gello"]
        };
        for (var k = 0; k < multipletimeandplace.length; k++) {
          classinfo.classSections.daysOfWeek = multipletimeandplace[
              k
              ].daysOfWeek.map((a) => dayInt[a]);
          classinfo.classSections.startTime = multipletimeandplace[k].beginTime;
          classinfo.classSections.endTime = multipletimeandplace[k].endTime;
          multipleevents.push(classinfo);
        }
        return multipleevents;
      }
    },
    manuallyFixCSS: function () {
      // This removes the "allDaySlot". The Vue plugin for FullCalendar does not remove it
      // even though it is configured to remove it
      $(".fc-day-grid").remove();
      $(".fc-divider.fc-widget-header").remove();

      // Remove empty toolbar
      $(".fc-toolbar").remove();
    },
    columnHeaderText: function (date) {
      switch (date.getDay()) {
        case 1:
          return "Mon";
        case 2:
          return "Tue";
        case 3:
          return "Wed";
        case 4:
          return "Thu";
        case 5:
          return "Fri";
        case 6:
          return "Sat";
        default:
          return " ";
      }
    },
    // calculateUnits: function (schedule, courses) {
    //   var total = 0;
    //   schedule.classes.forEach((item) => {
    //     const course = courses.find(
    //         (course) => course.courseId == item.courseId
    //     );
    //     total += course.unitsFixed;
    //   });
    //   return total;
    // },
    // /**
    //  * POSTS the given schedule to the backend for storage. Sets the quarter, name, units, and userEmail properties on the schedule.
    //  */
    // saveSchedule: function (schedule) {
    //   if (this.$store.getters.userIsAuthenticated) {
    //     //if user isn't logged in, nothing happens
    //     this.savingScheduleInProgress = true;
    //     $("span").css("pointer-events", "none"); //anything in a span will be disabled
    //     schedule.quarter = this.quarter;
    //     schedule.userEmail = this.$store.getters.userInfo.email;
    //     schedule.name = xss(schedule.name);
    //     schedule.totalUnits = this.calculateUnits(
    //         schedule,
    //         this.coursesComputed
    //     );
    //
    //     api
    //         .saveSchedule(schedule)
    //         .then((response) => {
    //           schedule.id = response.data;
    //           this.scheduleSavedStatus = "successful";
    //         })
    //         .catch((error) => {
    //           console.error(error);
    //           this.scheduleSavedStatus = "failed";
    //         });
    //     this.savingScheduleInProgress = false; // Either case, release the button
    //     $("span").css("pointer-events", "auto");
    //     this.$set(schedule, 'favorited', true);
    //     this.$forceUpdate();
    //   }
    // },
    // /*
    //  * Removes the favorite status from a schedule, Removes the schedule from the backend,
    //  * delivers a toast showing that it has been deleted.
    //  */
    // unFavoriteSchedule: async function (schedule) {
    //   if (this.$store.getters.userIsAuthenticated) {
    //     const resp = await api.deleteSchedule(schedule);
    //     if (resp.status > 400) {
    //       return;
    //     } else {
    //       this.$bvToast.show('deleted-toast-' + this._uid);
    //       this.$set(schedule, 'favorited', false);
    //       this.$forceUpdate();
    //     }
    //   }
    // },
    // onClose() {
    //   this.popoverShow = false;
    // },
    // saveName: function () {
    //   this.scheduleName = xss(this.scheduleName);
    //   this.popoverShow = false;
    //   api
    //       .updateScheduleName(this.schedule.id, this.scheduleName)
    //       .then(() =>{
    //         // this.schedule.name = this.scheduleName;
    //         this.scheduleLocal.name = this.scheduleName;
    //       })
    //       .catch((error) => {
    //         this.errors.push(error);
    //       });
    // },
    // editSchedule: async function(schedule) {
    //   await this.$store.dispatch('initializeStoreAsync',schedule);
    //   this.$eventHub.$emit('generate-schedules', null);
    // }
  },
}
</script>

<!--<script>-->
<!--import FullCalendar from '@fullcalendar/core'-->
<!--import timeGridPlugin from "@fullcalendar/timegrid";-->
<!--document.addEventListener('DOMContentLoaded', function() {-->
<!--  var calendarEl = document.getElementById('calendar');-->

<!--  var calendar = new FullCalendar.Calendar(calendarEl, {-->
<!--    eventClick: function(info) {-->
<!--      var eventObj = info.event;-->

<!--      if (eventObj.url) {-->
<!--        alert(-->
<!--            'Clicked ' + eventObj.title + '.\n' +-->
<!--            'Will open ' + eventObj.url + ' in a new tab'-->
<!--        );-->

<!--        window.open(eventObj.url);-->

<!--        info.jsEvent.preventDefault(); // prevents browser from following link in current tab.-->
<!--      } else {-->
<!--        alert('Clicked ' + eventObj.title);-->
<!--      }-->
<!--    },-->
<!--    initialDate: '2023-02-15',-->
    // events: [
    //   {
    //     title: 'simple event',
    //     start: '2023-02-02'
    //   },
    //   {
    //     title: 'event with URL',
    //     url: 'https://www.google.com/',
    //     start: '2023-02-03'
    //   }
    // ]
//   });
//
//   calendar.render();
// });
<!--</script>-->

<style>
@import "~@fullcalendar/core/main.css";
@import "~@fullcalendar/timegrid/main.css";
@import "~@fullcalendar/daygrid/main.css";

/* Transparent background. Fix for issue #78 */
.fc-unthemed td.fc-today {
  background: #dee2e600;
}

#inner-box > * {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  width: 65%;
  z-index: 999;
}

.no-wrap {
  overflow: hidden;
  white-space: nowrap;
}

.fc-title {
  font-size: 11px;
}

</style>

<!-- steven: to reduce top/bottom padding in schedule header -->
<style scoped>
.card-header {
  padding: 0;
}

.no-wrap.d-flex.flex-row.align-items-center {
  position: relative;
  padding-left: 5%;
}

</style>
